apiVersion: v1
kind: Secret
metadata:
  name: {{ include "respond.name" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
    app: {{ include "respond.name" . }}
type: Opaque
stringData:
  {{- if .Values.secrets.databaseUrl }}
  DATABASE_URL: {{ .Values.secrets.databaseUrl | quote }}
  {{- end }}
  TWILIO_AUTH_TOKEN: {{ .Values.secrets.twilioAuthToken | quote }}
  {{- if .Values.secrets.bootstrapAdmins }}
  BOOTSTRAP_ADMINS: {{ .Values.secrets.bootstrapAdmins | quote }}
  {{- end }}
