apiVersion: v1
kind: Secret
metadata:
  name: {{ include "respond.name" . }}
  labels:
    app: {{ include "respond.name" . }}
type: Opaque
stringData:
  {{- if .Values.secrets.databaseUrl }}
  DATABASE_URL: {{ .Values.secrets.databaseUrl | quote }}
  {{- end }}
  FS_SHARED_SECRET: {{ .Values.secrets.fsSharedSecret | quote }}
  VOIPMS_USERNAME: {{ .Values.secrets.voipmsUsername | quote }}
  VOIPMS_PASSWORD: {{ .Values.secrets.voipmsPassword | quote }}
  VOIPMS_DID: {{ .Values.secrets.voipmsDid | quote }}
  {{- if .Values.secrets.bootstrapAdmins }}
  BOOTSTRAP_ADMINS: {{ .Values.secrets.bootstrapAdmins | quote }}
  {{- end }}
