apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "respond.name" . }}-sms-tree
  labels:
    app: {{ include "respond.name" . }}
data:
  sms-tree.yaml: |
{{ .Values.smsTree.content | indent 4 }}
